---

- hosts: 172.31.0.101
  become: yes
  tasks: 
  - name: Install Apache2 Packages
    apt: name=apache2 state=present 

  - name: Start Apache Service
    service: name=apache2 state=started 



- hosts: web
  become: yes
  tasks: 
  - name: Install Apache2 Packages
    apt: name=apache2 state=present 

  - name: Start Apache Service
    service: name=apache2 state=started 



- hosts: web
  become: yes
  tasks: 
  - name: Checking Kernel Details
    command: 'uname -a'

